/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarCard: typeof import('./components/CalendarCard.vue')['default']
    CalendarView: typeof import('./components/CalendarView.vue')['default']
    ConfirmationDialog: typeof import('./components/ConfirmationDialog.vue')['default']
    ErrorText: typeof import('./components/reusableComponents/ErrorText.vue')['default']
    LeaveRequestCollection: typeof import('./components/LeaveRequestCollection.vue')['default']
    LeaveRequestList: typeof import('./components/LeaveRequestList.vue')['default']
    RegisterLeave: typeof import('./components/RegisterLeave.vue')['default']
    TitleComponent: typeof import('./components/reusableComponents/TitleComponent.vue')['default']
    TravelLeave: typeof import('./components/TravelLeave.vue')['default']
    VButton: typeof import('./components/reusableComponents/VButton.vue')['default']
    VButtonIcon: typeof import('./components/reusableComponents/VButtonIcon.vue')['default']
    VDialog: typeof import('./components/reusableComponents/VDialog.vue')['default']
    VDisclosure: typeof import('./components/reusableComponents/VDisclosure.vue')['default']
    VDropdown: typeof import('./components/reusableComponents/VDropdown.vue')['default']
    VInput: typeof import('./components/reusableComponents/VInput.vue')['default']
    VSwitch: typeof import('./components/reusableComponents/VSwitch.vue')['default']
    VTabGroup: typeof import('./components/reusableComponents/VTabGroup.vue')['default']
  }
}
